apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ttc-cluster
  namespace: ttc-race
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    # Note: No 'replicas' here, they are managed by the NodePool above
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: 127.0.0.1
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30773
          brokers:
            - broker: 0
              advertisedHost: 192.168.49.2
              nodePort: 30773
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}